version: "1.1"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    image: #TODO:image in gitlab
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.jpa.show-sql": "true",
        "webshop.app.jwtCookieName":"$SPRING_JWT_NAME",
        "webshop.app.jwtSecret":"$SPRING_JWT_KEY",
        "webshop.app.jwtExpirationMs":"$SPRING_JWT_TIME"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  frontend:
    image: registry.gitlab.com/teivys04/webshop/frontend
    ports:
      -  $NODE_LOCAL_PORT
    stdin_open: true
    tty: true
volumes:
  db:

